export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "RODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "RODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "RODUCT_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";